version: '3.8'

services:
  app:
    build: .
    container_name: nestjs_app
    entrypoint: wait-for db:3306 -t 40 -- ./.docker/entrypoint.sh
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  db:
    container_name: db
    build: ./.docker/mysql
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fin
      - MYSQL_ROOT_PASSWORD=root
